<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="LAPTOP-5150QTI9" name="pytest" skipped="0" tests="2" time="0.054" timestamp="2020-03-22T14:21:11.602917"><testcase classname="test_sample1" file="test_sample1.py" line="3" name="test_file1_method1" time="0.003"><failure message="AssertionError: test failed because x=5 y=6
assert 5 == 6
  +5
  -6">@pytest.mark.set1
    def test_file1_method1():
        x = 5
        y = 6
        assert x + 1 == y, &quot;test failed because x=&quot; + str(x) + &quot; y=&quot; + str(y)
&gt;       assert x == y, &quot;test failed because x=&quot; + str(x) + &quot; y=&quot; + str(y)
E       AssertionError: test failed because x=5 y=6
E       assert 5 == 6
E         +5
E         -6

test_sample1.py:9: AssertionError</failure></testcase><testcase classname="test_sample1" file="test_sample1.py" line="11" name="test_file1_method2" time="0.001"></testcase></testsuite></testsuites>